# This is just a best-guess because there's no trial version of Nexus IQ Server to test against
trigger:
  paths:
    exclude:
      - .github
      - .vscode/*
pool:
  name: Default
variables:
  ModuleName: NexusIQ

steps:
  - task: CopyFiles@2
    displayName: Copy the module files to artifact staging directory
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: |
        NexusIQ.ps*
        README.md
        LICENSE
      TargetFolder: $(Agent.TempDirectory)/${{variables.ModuleName}}

  - pwsh: |
      Import-Module ./$env:ModuleName -Verbose
      $Splat = @{
        BaseUrl = $env:BaseUrl
        APIVersion = "v2"
        Credential = [pscredential]::new($env:UserCode,$($env:PassCode | ConvertTo-SecureString -AsPlainText -Force))
      }
      Connect-NexusIQ @Splat
    displayName: 'Set up Nexus IQ connection profile'
    env:
      BaseUrl: https://nexusiq.myorg.com
      UserCode: $(UserCode)
      PassCode: $(PassCode)
      ModuleName: ${{variables.ModuleName}}

  - pwsh: ./Build/Install-Pester.ps1
    displayName: Install Pester V5

  - pwsh: ./Build/Start-Tests.ps1
    displayName: Run Pester Tests
    enabled: false
    env:
      ModuleName: ${{variables.ModuleName}}

  - task: PublishTestResults@2
    displayName: Publish Test Results
    enabled: false
    inputs:
      testRunTitle: 'Test Results for ${{variables.ModuleName}}'
      testRunner: NUnit
      testResultsFiles: '$(Agent.TempDirectory)/Pester/test-results.xml'
      failTaskOnFailedTests: true
      mergeTestResults: true

  - task: PublishCodeCoverageResults@2
    displayName: Publish Code Coverage
    enabled: false
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/reports/coverage.xml'
      pathToSources: '$(Pipeline.Workspace)/${{variables.ModuleName}}'

  - pwsh: ./Build/Register-PSGallery.ps1
    displayName: Register PSGallery

  - task: UseDotNet@2
    displayName: Use Dotnet 8.x
    inputs:
      version: 8.x

  - pwsh: ./Build/Publish-Module.ps1
    displayName: Publish the module
    # condition: and(succeeded(),eq(variables['Build.SourceBranchName'],'main'))
    env:
      ModuleName: ${{variables.ModuleName}}
      NuGetApiKey: $(NuGetApiKey)
      ModulePath: $(Agent.TempDirectory)/${{variables.ModuleName}}

  - pwsh: |
      $UserHomeFolder = switch (Test-Path Env:\APPDATA)
      {
        $true { $env:APPDATA }
        $false { $HOME }
      }
      (Resolve-Path "$UserHomeFolder/$env:ModuleName").Path | Remove-Item -Recurse -Verbose
    displayName: Remove the credentials
    condition: always()
    env:
      ModuleName: ${{variables.ModuleName}}
